name: Deploying via GitHub Actions to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lifedrop-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lifedrop-frontend:latest ./frontend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lifedrop-backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lifedrop-frontend:latest
